AdmiralDS/react-ui

- src/components/Table/Table.stories.tsx
- src/components/Table/data.tsx
- src/components/Table/index.tsx
- src/components/Table/mixins.ts
- src/components/Table/style.ts
1) add opportunity to use extraText in Header
2) fix problem with header background when greyHeader={true} and displayRowSelectionColumn={true}
> Add extraText, fix header background

- package.json
- src/icons/IconComponents-documents.ts
- src/icons/IconComponents-service.ts
- src/icons/IconComponents-system.ts
- vite.config.ts
Откат изменений, повлекших за собой прекращение работы библиотеки с webpack module federation
> fix(ModuleFederation)

- src/components/Table/index.tsx
Возможность передать кастомную обертку для строки дает возможность интегрировать механизма по перемещению строк
> Возможность передать кастомную обертку для строки

- src/components/form/SelectField/SelectField.stories.tsx
- src/components/input/Select/index.tsx
feat(Select): fix firing onBlur event
> feat(Select): duplicate input value on cmd+a

- packages/react-ui/src/components/input/Select/MultipleSelectChips/styled.ts
- packages/react-ui/src/components/input/Select/Option/DropDownOption.tsx
fix disabled chip border && remove checkbox redundant readOnly state
> fix(Select): fix disabled chip border

- packages/react-ui/src/components/Checkbox/Checkbox.stories.tsx
- packages/react-ui/src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/react-ui/src/components/Checkbox/index.tsx
- packages/react-ui/src/components/CheckboxCompositeGroup/__snapshots__/CheckboxCompositeGroup.test.tsx.snap
- packages/react-ui/src/components/CheckboxGroup/__snapshots__/CheckBoxGroup.test.tsx.snap
- packages/react-ui/src/components/SelectTree/__snapshots__/SelectTree.test.tsx.snap
- packages/react-ui/src/components/form/CheckboxField/__snapshots__/CheckboxField.test.tsx.snap
- packages/react-ui/src/components/form/CheckboxField/index.tsx
- packages/react-ui/src/components/input/Select/Option/DropDownOption.tsx
fix checkbox color in Select drop container for multiple mode
> fix(Select): fix checkbox color in Select drop container 

- src/components/Tree/Stories/Tree.stories.tsx
- src/components/Tree/TreeNode.tsx
- src/components/Tree/index.tsx
> fix(Tree): Изменены отступы уровней дерева в соответствии с дизайном.

- .storybook/preview.tsx
- src/components/input/PhoneNumberInput/index.tsx
добавлена дефолтная иконка при отсутствии совпадений с кодами стран
#971
> fix(PhoneNumberInput): Убрана иконка очистки выбранного значения

- src/components/input/Select/Select.test.tsx
> test(Select): Исправлены тесты

- src/components/Tree/Stories/Templates/SimpleTree.tsx
- src/components/Tree/index.tsx
> fix(Tree): Убран рудиментарный атрибут width

- src/components/input/Select/index.tsx
- src/components/input/Select/stories/SearchSelect.stories.tsx
- src/components/input/Select/stories/searchSelect/SearchSelectExternalFilter.template.tsx
- src/components/input/Select/stories/select/SelectCustomRenderMultipleValues.template.tsx
Исправлена ошибка стирания из стейта выбранных опций при внешней фильтрации значений в режиме multiple, доработан пример внешней фильтрации в storybook
#1086
> fix(Select): Исправлена ошибка стирания из стейта выбранных опций

- src/components/Menu/MenuItem.tsx
- src/components/Menu/index.tsx
- src/components/Menu/stories/MenuMultiLevel.template.tsx
> fix(Menu): Исправлена ошибка с "подвисанием" подменю при скролле

- src/components/Menu/MenuItem.tsx
- src/components/Menu/index.tsx
> Исправлена обработка события onLeave для MenuItem

- src/components/Menu/index.tsx
- src/components/common/utils/splitDataAttributes.ts
- src/components/input/Select/index.tsx
- src/components/input/Select/stories/searchSelect/SearchSelectWithAddButton.template.tsx
для dropDownContainer и Menu
#1117
> feat(Select): добавлена возможность передавать data-attribute 

- src/components/Menu/VirtualBody.tsx
- src/components/Menu/index.tsx
- src/components/Menu/stories/MenuVirtualScroll.template.tsx
- src/components/Menu/utils.ts
добавлена возможность использовать в многоуровневом меню
#1073
> feat(Menu): виртуальный скролл 

- src/components/Tree/TreeNode.tsx
- src/components/Tree/index.tsx
> fix(Tree): убраны лишние ререндеры при наведении на элементы

- src/components/input/PhoneNumberInput/index.tsx
> fix(PhoneNumberInput): Исправлено смещение иконки флага при изменении line-height на контейнере

- src/components/Tree/index.tsx
- src/components/Tree/stories/Tree.stories.tsx
- src/components/Tree/stories/TreeWithControlCheckCount.template.tsx
- Исправлена ошибка расчета состояния checked в дочерних узлах
- Добавлен пример в storybook
#1337
> Исправлена ошибка расчета состояния checked в дочерних узлах

- src/components/Menu/MenuItem.tsx
- src/components/Menu/index.tsx
- src/components/Menu/menuItemMixins.ts
- src/components/Menu/stories/Menu.stories.tsx
- src/components/Menu/stories/MenuWithPreselect.template.tsx
> В меню добавлено состояние preselected

- src/components/input/Select/stories/SearchSelect.stories.tsx
> chore(Select): добавлена документация для Multiple с кастомными опциями

- src/components/Tree/index.tsx
> исправлена типизация при фильтрации items

- src/components/input/PhoneNumberInput/index.tsx
- src/components/input/PhoneNumberInput/stories/PhoneNumberInput.stories.tsx
- src/components/input/PhoneNumberInput/stories/PhoneNumberInputWithPlaceholder.template.tsx
> Feat(PhoneNumberInput): Добавлен функционал placeholder для компонента

- src/components/MenuButton/stories/MenuButton.stories.tsx
- src/components/MenuButton/stories/MenuButtonMultiLevel.template.tsx
> Docs(MenuButton): Добавлен в Story варианта с многоуровневым меню

- src/components/input/Select/stories/SearchSelect.stories.tsx
- src/components/input/Select/stories/data.ts
- src/components/input/Select/stories/searchSelect/SearchSelectWithChooseAllButton.template.tsx
> feat: add multiSearchSelect with add choose all button

- src/components/Menu/index.tsx
> fix(Menu): Fix hover effect does not disappear when the cursor is moved away from the menu

- src/components/Button/__snapshots__/Button.test.tsx.snap
- src/components/Menu/index.tsx
- src/components/MultiButton/__snapshots__/MultiButton.test.tsx.snap
> Fix(SelectField): Исправлено появление белых пропусков в списке опций

- src/components/input/Select/styled.ts
Fix(Select): Исправлено tooltip не показывается, если компонент readOnly или disabled
#1604
> Fix(Select): tooltip

- src/components/input/Select/index.tsx
> fix(Select) -  Исправлена проблема с tab

- src/components/Button/__snapshots__/Button.test.tsx.snap
- src/components/MultiButton/__snapshots__/MultiButton.test.tsx.snap
- src/components/input/MultiInput/index.tsx
- src/components/input/MultiInput/stories/MultiInput.stories.tsx
- src/components/input/MultiInput/stories/MultiInputWithIcons.template.tsx
- src/components/input/MultiInput/styled.ts
Добавлена возможность отображать иконки в начале и конце поля
#1745
> feat(MultiInput) - iconsBefore & iconsAfter

- src/components/Button/__snapshots__/Button.test.tsx.snap
- src/components/Menu/index.tsx
- src/components/MultiButton/__snapshots__/MultiButton.test.tsx.snap
Обновлены snapshots тестов кнопок
> Fix(Menu): Убран лишний css mixin hideNativeScroll #1732

- src/components/ProgressHeader/index.tsx
- src/components/ProgressPage/__snapshots__/ProgressPage.test.tsx.snap
- src/components/ProgressPage/index.tsx
- src/components/ProgressStepper/__snapshots__/ProgressStepper.test.tsx.snap
- src/components/ProgressStepper/index.tsx
Больше не создаем отдельный стиль на каждое значение процента
> feat: Небольшая оптимизация для прогресс-баров

- src/components/input/Select/index.tsx
- src/components/input/Select/stories/searchSelect/SearchSelectLoadingOnScroll.template.tsx
Исправлена ошибка в подгрузке данных при scroll, обновлен пример в storybook
#1754
> Fix(Select) load on scroll

- src/components/input/Select/styled.ts
> Fix(Select): Исправлена ошибка отображения chip для  размера S

- src/components/DropdownContainer/index.tsx
: Исправлена некорректная работа компонента на touch устройствах
> fix(DropdownContainer)
